# Generated by Django 3.1.5 on 2021-11-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('types', models.CharField(choices=[('Seance unique', 'Seance unique'), ('Formule 5 seances', 'Formule 5 seances')], default='CASH', max_length=100)),
                ('description', models.TextField(default='this is a default message.')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('formule', models.CharField(choices=[('Seance unique', 'Seance unique'), ('Formule 5 seances', 'Formule 5 seances')], default='Seance unique', max_length=100)),
                ('status', models.CharField(choices=[('NOTPAID', 'NOTPAID'), ('AVOIR', 'AVOIR'), ('PAID', 'PAID')], default='NOTPAID', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
            ],
        ),
    ]
