# Generated by Django 3.1.5 on 2021-11-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_auto_20211107_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='formule',
            field=models.CharField(choices=[('', 'Choose...'), ('Seance unique', 'Seance unique'), ('Formule 5 seances', 'Formule 5 seances')], default='Seance unique', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('', 'Choose...'), ('NOTPAID', 'NOTPAID'), ('AVOIR', 'AVOIR'), ('PAID', 'PAID')], default='NOTPAID', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='types',
            field=models.CharField(choices=[('', 'Choose...'), ('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], default='CASH', max_length=100),
        ),
    ]
