# Generated by Django 3.1.5 on 2021-11-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_auto_20211108_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=35000, max_digits=10),
            preserve_default=False,
        ),
    ]
