# Generated by Django 3.1.5 on 2021-11-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_invoice_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('', 'Choose...'), ('NOTPAID', 'NON PAYER'), ('AVOIR', 'AVOIR'), ('PAID', 'PAYER')], default='NOTPAID', max_length=100),
        ),
    ]
