# Generated by Django 3.1.5 on 2021-11-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_auto_20211110_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
    ]
